# render.yaml
services:
  - type: web
    name: annonces-immo-ci
    plan: free
    env: python
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt
      export FLASK_APP=app.py
      export FLASK_ENV=production
      python init_db.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1 --max-requests 1000 --preload
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        # REMPLACEZ par votre vraie URL Supabase PostgreSQL
        value: postgresql://postgres:[PASSWORD]@db.[PROJECT_REF].supabase.co:5432/postgres
      - key: CLOUDINARY_CLOUD_NAME
        value: dbn8ees4r
      - key: CLOUDINARY_API_KEY
        value: "118479922956157"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PHONE
        value: "+2250506531522"
      - key: ADMIN_PASSWORD
        sync: false