# render.yaml
services:
  # Application Web Flask
  - type: web
    name: annonces-immo-ci  # Nom clair, proche de ton projet
    plan: free
    env: python
    region: frankfurt  # Plus proche de la CI que "oregon"
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head  # Applique les migrations → crée les tables
      python create_admin_auto.py  # Crée l'admin après les tables
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false  # ⚠️ À remplir manuellement avec l'URL Supabase ou Render DB
      - key: CLOUDINARY_CLOUD_NAME
        value: dbn8ees4r
      - key: CLOUDINARY_API_KEY
        value: "118479922956157"
      - key: CLOUDINARY_API_SECRET
        sync: false  # 🔐 Saisir manuellement dans Render
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PHONE
        value: "+2250506531522"
      - key: ADMIN_PASSWORD
        sync: false  # 🔐 Saisir manuellement (mot de passe admin)
    healthCheckPath: /